version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flyx
      POSTGRES_USER: flyx_user
      POSTGRES_PASSWORD: flyx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
